# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "651b04dda6e76910a72e5a04fef4ec97"
name = "Chatty Helpdesk"
application_url = "https://admin.shopify.com/store/test-store-1100000000000000000000000000000003476/apps/chatty-helpdesk"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]
