const shopifyConfig = {
  apiKey: process.env.SHOPIFY_API_KEY,
  apiSecret: process.env.SHOPIFY_API_SECRET,
  appUrl: process.env.APP_URL,
  scopes: process.env.SHOPIFY_SCOPES || 'read_products,write_products,read_orders,write_orders,read_draft_orders,write_draft_orders,read_fulfillments,write_fulfillments,read_inventory,write_inventory,read_themes,write_themes,read_customers,write_customers,read_content,write_content,read_script_tags,write_script_tags,read_shipping,write_shipping,read_analytics,read_checkouts,write_checkouts,read_reports,write_reports,read_price_rules,write_price_rules,read_discounts,write_discounts,read_marketing_events,write_marketing_events,read_locations,read_gift_cards,write_gift_cards,read_assigned_fulfillment_orders,write_assigned_fulfillment_orders,read_merchant_managed_fulfillment_orders,write_merchant_managed_fulfillment_orders,read_third_party_fulfillment_orders,write_third_party_fulfillment_orders,read_files,write_files,read_translations,write_translations,read_locales,write_locales,read_shopify_payments_payouts,read_shopify_payments_disputes,read_online_store_pages,write_online_store_pages,read_online_store_navigation,write_online_store_navigation,read_metaobjects,write_metaobjects,read_metaobject_definitions,write_metaobject_definitions,read_publications,write_publications,read_product_listings,read_product_feeds,read_markets,write_markets,read_custom_pixels,write_custom_pixels',
  apiVersion: '2026-01'
};

export default shopifyConfig;
